# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Kaho Bar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kaho Bar
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'SDWebImage', '~> 5.0'

end
